version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in S3 bucket..."
      - aws s3 sync build/ s3://react-s3-codebuild --delete
